---
Monitored web sites:
  monedo:
    url: 'https://www.monedo.com/'
    # number of seconds between polling website. It's highly recommended that
    # this time is at least 10x smaller than fetch time for paired service - db publisher
    request sleep: 60
    expected pattern: '<h1.*?>Monedo is where the best finance and tech brains come together</h1>'

Metrics collection endpoint:
  aiven:
    broker:
      type: kafka
      host: 'kafka-3b71190f-project-7747.aivencloud.com'
      port: 26867
      auth: ssl
  docker:
    broker:
      type: kafka
      host: 'localhost'
      port: 9092
      auth: no_auth
